
package com.mycompany.mavenproject1.Views;

import com.mycompany.mavenproject1.IOFile.IOSanPham;
import com.mycompany.mavenproject1.Object.SanPham;
import com.mycompany.mavenproject1.Object.SuKien;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class KhoHangViews extends javax.swing.JFrame {
    
    private ArrayList<SanPham> list;
    private ArrayList<SuKien> list_SuKien;
    DefaultTableModel model;
    int key =0;
    IOSanPham io = new IOSanPham();
    /**
     * Creates new form KhoHangViews
     */
    public KhoHangViews() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new ArrayList<> (); // list = io.docSP();
        list_SuKien = new ArrayList<> ();
        model = (DefaultTableModel)jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        tieudekhohang = new javax.swing.JLabel();
        LabelTen = new javax.swing.JLabel();
        LabelGiaNhap = new javax.swing.JLabel();
        TFTen = new javax.swing.JTextField();
        LabelGiaBan = new javax.swing.JLabel();
        LabelSoLuongNhap1 = new javax.swing.JLabel();
        TFGiaNhap = new javax.swing.JTextField();
        TFSoLuongNhap = new javax.swing.JTextField();
        TFGiaBan = new javax.swing.JTextField();
        LabelTheLoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TFTheLoai = new javax.swing.JTextField();
        BtnInsert = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(778, 582));

        tieudekhohang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tieudekhohang.setText("THÔNG TIN SẢN PHẨM");

        LabelTen.setText("Tên ");

        LabelGiaNhap.setText("Giá Nhập");

        TFTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTenActionPerformed(evt);
            }
        });

        LabelGiaBan.setText("Giá Bán");

        LabelSoLuongNhap1.setText("Số lượng ");

        TFGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFGiaNhapActionPerformed(evt);
            }
        });

        TFSoLuongNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSoLuongNhapActionPerformed(evt);
            }
        });

        TFGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFGiaBanActionPerformed(evt);
            }
        });

        LabelTheLoai.setText("Thể Loại");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Giá Nhập", "Giá Bán", "Số lượng", "Thể loại"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TFTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTheLoaiActionPerformed(evt);
            }
        });

        BtnInsert.setText("INSERT");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(BtnInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnClear)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFTheLoai))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelSoLuongNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFSoLuongNhap))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFGiaNhap))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelTen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tieudekhohang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TFTen)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LabelGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFGiaBan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tieudekhohang)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSoLuongNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnClear)
                            .addComponent(BtnInsert)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTenActionPerformed

    private void TFGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFGiaNhapActionPerformed

    private void TFSoLuongNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSoLuongNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSoLuongNhapActionPerformed

    private void TFGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFGiaBanActionPerformed

    private void TFTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTheLoaiActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        // TODO add your handling code here:
        SanPham sp=null;
        
        for (int i =0; i <list.size();i++){
            if(list.get(i).getTensanpham().equals(TFTen.getText())){
                sp = list.get(i);
//              list.add(sp);
                key = 1;
                break;
            }
        }
        if (key ==0){
            sp = new SanPham(TFTen.getText(),Integer. parseInt(TFGiaNhap.getText()),Integer. parseInt(TFGiaBan.getText()));
            list.add(sp);
        }
        key =0;
        Date ngay = new Date();
        SuKien sk = new SuKien(sp,ngay,"mua",Integer. parseInt(TFSoLuongNhap.getText()));
        sk.isRealSK();
        list_SuKien.add(sk);
        showResult(); /// Bảng hiện thêm hàng do hàm showResult này còn danh sách list vẫn chỉ có các sản phẩm ko cùng tên
        io.ghiSP(list);
//        io.ghiSK(list_SuKien);
        
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        JFrame MainViews = new MainViews();
        this.setVisible(false);
        MainViews.setVisible(true);
        
    }//GEN-LAST:event_BtnBackActionPerformed
    private void showResult() { 
        SanPham sp = list.get(list.size()-1);
        model.addRow(new Object[]{
            sp.getTensanpham(), sp.getGianhap(),sp.getGiaban(),sp.soluong,1
        });        
    }
    
//    public static void main(String args[]) {
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KhoHangViews().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JLabel LabelGiaBan;
    private javax.swing.JLabel LabelGiaNhap;
    private javax.swing.JLabel LabelSoLuongNhap1;
    private javax.swing.JLabel LabelTen;
    private javax.swing.JLabel LabelTheLoai;
    private javax.swing.JTextField TFGiaBan;
    private javax.swing.JTextField TFGiaNhap;
    private javax.swing.JTextField TFSoLuongNhap;
    private javax.swing.JTextField TFTen;
    private javax.swing.JTextField TFTheLoai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tieudekhohang;
    // End of variables declaration//GEN-END:variables

    
}
