/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package View;

import ThanhToan.HoaDon;

/**
 *
 * @author XPS
 */
public class HoaDonView extends javax.swing.JFrame {

    HoaDon HD;

    /**
     * Creates new customizer HoaDonView
     */
    public HoaDonView(HoaDon hd) {
        this.HD = hd;
        initComponents();
        String text = "";
        for (int i = 0; i < this.HD.getDanhSachSanPham().size(); ++i) {
            text = text + "\n" + (i + 1) + ". " + this.HD.getDanhSachSanPham().get(i) + "*" + this.HD.getDanhSachSoLuong().get(i);
        }
        text += "\n-----------------------------------";
        text += "\n" + "Tong gia tri hoa don: " + this.HD.tongHoaDon();
        jTextArea2.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("HÓA ĐƠN THANH TOÁN");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel4);

        jLabel2.setText("Ngày "+this.HD.ngayThanhToan());
        jPanel3.add(jLabel2);
        jPanel3.add(jPanel5);
        jPanel3.add(jPanel6);

        jTextArea2.setColumns(40);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane2);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
