/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import IO.IO;
import NhanVien.NVPartTime;
import NhanVien.NhanVien;
import NhanVien.NhanVienCoDinh;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhanVienDuc extends javax.swing.JFrame {

    private ArrayList<NhanVien> list_NhanVien;

    DefaultTableModel model;
    int key = 0;
    IO io = new IO();
    public NhanVienDuc() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
//        list = new ArrayList<> (); // list = io.docSP();
        list_NhanVien = new ArrayList<>();
        model = (DefaultTableModel) jTable1.getModel();
        list_NhanVien = io.docNV();
//        System.out.println(list_NhanVien.size());
        showResultCPNV();
    }

        private void showResultCPNV() {

        for (int i = 0; i < list_NhanVien.size(); i++) {
            NhanVien nv = list_NhanVien.get(i);
            model.addRow(new Object[]{
                nv.getTenNhanVien(), nv.getLoaiNhanVien(), (int)nv.tinhLuong()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LbtenNhanVien = new javax.swing.JLabel();
        LbtenNhanVien1 = new javax.swing.JLabel();
        TFtenNhanVien = new javax.swing.JTextField();
        BtnTimKiem = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Nhân Viên", "Part or Full", "Tiền Lương"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LbtenNhanVien.setText("Tên nhân viên");

        LbtenNhanVien1.setText("Tên nhân viên");

        BtnTimKiem.setText("Tìm Kiếm");
        BtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimKiemActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LbtenNhanVien1)
                .addGap(18, 18, 18)
                .addComponent(TFtenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BtnTimKiem)
                .addGap(18, 18, 18)
                .addComponent(BtnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(LbtenNhanVien)
                    .addContainerGap(233, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbtenNhanVien1)
                    .addComponent(TFtenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTimKiem)
                    .addComponent(BtnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(LbtenNhanVien)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimKiemActionPerformed
        // TODO add your handling code here:
        NhanVien nv = null;

        for (int i = 0; i < list_NhanVien.size(); i++) {
            if (list_NhanVien.get(i).getTenNhanVien().equals(TFtenNhanVien.getText())) {
                nv = list_NhanVien.get(i);
                //              list.add(sp);
                showResultTKNV(nv);
            }
        }
    }//GEN-LAST:event_BtnTimKiemActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        String text = "";
        jTextArea1.setText(text);
    }//GEN-LAST:event_BtnClearActionPerformed

    private void showResultTKNV(NhanVien nv) {
        String text = "";
        if (nv instanceof NhanVienCoDinh) {

            text += "Nhan vien co dinh:\n";
            text += "Ho va ten: " + ((NhanVienCoDinh) nv).getTenNhanVien() + "\n";
            text += "Vi tri: " + ((NhanVienCoDinh) nv).getViTri() + "\n";
            text += "Luong: " + (int)((NhanVienCoDinh) nv).tinhLuong() + "\n";
        } else if (nv instanceof NVPartTime) {
            text += "Nhan vien Past-Time:\n";
            text += "Ho va ten: " + ((NVPartTime) nv).getTenNhanVien() + "\n";
            text += "Vi tri: " + ((NVPartTime) nv).getThoiGianLamViec() + "\n";
            text += "Luong: " + (int)((NVPartTime) nv).tinhLuong() + "\n";
        }

        jTextArea1.append(text);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnTimKiem;
    private javax.swing.JLabel LbtenNhanVien;
    private javax.swing.JLabel LbtenNhanVien1;
    private javax.swing.JTextField TFtenNhanVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
